### ISSUE TITLE
update-DEV-from-Git.cmd

### ISSUE THREAD

**Issue by andy040670** [vortigont/FireLamp_JeeUI#105]
А куда делся update-DEV-from-Git.cmd ???
В билдере теперь не возможно переключиться между ветками и обновить локальный репо.

**Comment by andy040670** [comment]
Ссылка на форум в вебморде была не лишней.
Мне вот телега нафиг не нужна, я ей не пользуюсь, хоть и бот мой там трудится, собирает нужную информацию с моего сервера, но без необходимости туда даже не заглядываю.

**Comment by vortigont** [comment]
@andy040670 ветка `DEV` уже давно не используется и никаких изменений туда не вливается. Отдельные новые функции я вливаю из разных веток через пулл-реквесты. Переключать ветки из скрипта больше не получится, т.к. заранее имя ветки неизвестно.
Сам cmd файл я могу вернуть если без него билдер не работает, но его функционал по сути сводится только к `git pull`.

Ссылку на форум поменял, т.к. на форуме давно уже ничего не происходит толком.
Если пользовались, оставлю обе.

**Comment by andy040670** [comment]
> Сам cmd файл я могу вернуть если без него билдер не работает, но его функционал по сути сводится только к `git pull`.

Там ещё архиполезная функция "сброс локального репозитория"
`	%gitcmd% reset --hard
	rem "%ProgramFiles%\Git\bin\git" checkout .
	%gitcmd% pull`
В самом билдере первый пункт переименовать в "Обновить локальный репозиторий (Мастер ветка)"
Второй пункт убрать из за неактуальности.

**Comment by andy040670** [comment]
Ссылки `<span class="menu-title"><a href="https://community.alexgyver.ru/threads/wifi-lampa-girljanda-informer-ws2812-hub75-obsuzhdenie-proshivki-firelamp_embui.7257/" target="_blank" rel="noopener noreferrer">Gyver</a></span>` в data/index.html.gz нет, соответственно в UI тоже её нет.

**Comment by vortigont** [comment]
html я не перепаковывал. Обновится вместе джейсонами при следующем изменении элементов в вебюи.
Можете пока положить хтмлку на ФС как есть и удалить имеющийся там .gz

**Comment by andy040670** [comment]
А, понятно. 
Да, я ручками всё сделал (перепаковал .gz).
