### ISSUE TITLE
Кукушка

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#108]
Стоит ограничение с 6 до 21. В 6 говорит ,в 21 молчит.Наверно логичней ,чтобы или говорила или молчала) И еще ,сильно муторно ,чтобы первая фраза была "доброе утро" ,а последняя "спокойной ночи" ?

**Comment by vortigont** [comment]
Сделал что бы "до" тоже включало.
Утро/вечер делать не буду. Во-первых этих файлов нет в плеере, во-вторых эти дополнительные фразы внесут новые проблемы с отловом начала/конца воспроизведения файлов голоса/часов.
Может желающие повозиться когда-нибудь добавят, класс плеера написан, разобраться будет не сложно.
