### ISSUE TITLE
эффект 8 - потеря динамического диапазона на малых значениях яркости

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#15]
При понижении яркости ,теряеться много деталей (пиксели тухнут) .На макс яркости ,как надо.

**Comment by dina16121974** [comment]
мастер есп 32.

**Comment by dina16121974** [comment]
Как то стартуют не правильно ,плотность тронешь ,всё нормализуеться.

**Comment by vortigont** [comment]
implemented in https://github.com/vortigont/FireLamp_JeeUI/commit/bb182d3abd5f583504a4d6b96ed7b655d97d1777
