### ISSUE TITLE
События

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#17]
Мастер есп 32. 1 Вкл. лампу работает ,но выводит левый текст null xv ?. 2 выкл. лампу работает. 3 будильник ,вроде всё работает (удивительно). 4 вывести текст работает. 5 вывести время ,время выводит ,озвучки нет. 6 ночник не работает. 7 светильник не работает. Остальное не проверял ,не знаю для чего нужно.

**Comment by dina16121974** [comment]
Aux не работает.

**Comment by vortigont** [comment]
> Aux не работает.

заводите отдельные тикеты и добавьте описание что настраивали в конфиге события.
Там настолько удодский и недокументированный формат что понять что происходит очень сложно.

**Comment by dina16121974** [comment]
Каждое действие ,в событиях отдельно расписывать ? События проверить после обновленной прошивке или на текущей ?

**Comment by vortigont** [comment]
одна отдельная проблема - один тикет. aux отдельный тикет, время отдельно и что там еще отдельно.
Если проблема закрыта - я закрою тикет целиком.
Проверять на актуальной версии конкретно для этой проблемы. Если не уверены - проверьте на разных ветках одинаковое ли поведение, ну или просто на фит ветке.

**Comment by vortigont** [comment]
старая система событий убрана, ждём новую реализазию
