### ISSUE TITLE
Микрофон vs Эффекты

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#18]
На мой взгляд вкл чекрыжек микрофона ,очень сильно мешает этим эффектам. 4,23,50,51,55

**Comment by dina16121974** [comment]
мастер есп 32

**Comment by vortigont** [comment]
для некоторых вроде ничего так - 4, 23, вполне. Ну остальное так - видно что реагирует, но насчет красивости спорно.

**Comment by dina16121974** [comment]
Вы на яркости 50 поглядите , у меня лампы на 50-80 работают, по мне так красивей ,мож плафоны такие. Я к чему или яркости добавить или чекрыжек к черту.

**Comment by dina16121974** [comment]
Яркости 4 и 23

**Comment by vortigont** [comment]
не понял. Если мало яркости - добавьте, если с микрофоном не нравится, отключите микрофон. Что нужно менять в коде-то?
Вообще есть планы переделать управление яркостью целиком.

**Comment by dina16121974** [comment]
Тогда подождем переделку.
