### ISSUE TITLE
Калибровка микрофона

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#19]
Мастер есп 32. Нормальная калибровка длиться 3-5 сек ,после в графе ,уровень шума в ед. выводит цифры ,я так думаю фоновый шум в децибелах. Здесь калибровка не работает.

**Comment by BashSer** [comment]
>Алгоритм магии, что бы всё работало(не знаю как оно в коде работает, описываю действия после которых становится "хорошо"):
> 1. Включить питание
> 2. Зайти в настройки кнопки, сделать выкл\вкл флажком, при необходимости проверить действия щелчков. Если что-то не работает, то зайти в это действие и выйти. Например OFF: 1 Click - ON, редактировать, не изменяя параметров просто нажать обновить
>> **3. Зайти в настройки микрофона, нажать калибровку, переключить флажок выкл\вкл, на экране так и подвиснет калибровка, но эффекты начинают хорошеечно реагировать на микрофон**
> 4. Зайти в настройки MQTT и выйти

>эту кнопку калибровки я уберу, она нефункциональна. Флажёк микрофона остается включеный после перезагрузки в настройках?
>Да, флажок остаётся активным в настройках микрофона после перезагрузки по питанию.

Не знаю, что происходит со стороны исполнения кода, но таким образом микрофон работает исправно и эффекты красиво реагируют на разные частоты микрофона MAX9814

**Comment by vortigont** [comment]
так, проверил у себя. После перезагрузки достаточно дернуть туда-сюда флажек микрофона, больше ничего дергать не надо. Т.е. не восстанавливается признак включения хотя флажек взведен. Реализация микрофона сейчас весьма топорная, ждет очереди на переписываение.
В короткой перспективе кнопку калибрации я уберу, восстановление включения поправлю.
