### ISSUE TITLE
Опционально восстанавливать состояние вкл/выкл при перезагрузке

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#24]
Фит 32. Надо ,что бы лампа стартовала  с  того режима в котором прекратила работу. Например выключил питание на работоющей лампе ,потом включил она заработала.

**Comment by vortigont** [comment]
некоторым надо, некоторым наоброт не надо. Раньше была опция сборки в конфиге. По-моему я  её выкинул. Надо сделать заново в виде доп. настроки

**Comment by dina16121974** [comment]
многие из розетки дергают )))
