### ISSUE TITLE
эффект "Огонь 2018" - не горит 16й столбец

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#3]
огонь 2018 кривой

**Comment by vortigont** [comment]
может он и должен быть кривым :) Огонь как огонь, не знаю какой должен быть.
Опишите толком чем не угодил.

**Comment by dina16121974** [comment]
щас огонь нормальный,только 1 ряда верт,пикселей с краю нету.

**Comment by dina16121974** [comment]
Теперь надо что бы при подаче питания на тм 1637 выводился текущий ип адресс подкл. Тогда с тм 1637 тему можно закрыть.

**Comment by vortigont** [comment]
про 1 ряд пикселей гляну, не обращал внимания.
По тм лучше отдельный тикет заведите, пожалуйста.
