### ISSUE TITLE
Хаб 75

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#35]
Эффекты которые ,не идут. 1 ,10 ,12  ,15 (половина панели работает) ,20 ,21 ,24 ,25 ,28 ,29 ,33 ,37 ,42 ,42 ,44 ,47 ,49 ,51, 56, 57, 59, 60, 65, 69, 70 (половина панели работает) ,71, 73, 254, 255. И еще чередование цветов ,не то. Надо где то настройку сделать.

**Comment by vortigont** [comment]
Поясните что значит (половина панели работает) и не идут. Я же не телепат. 1й эффект это белая заливка, что там может не работать-то? Шкалу крутили?
А чередование цветов меняется перетыканием проводков идущих в панель.

**Comment by dina16121974** [comment]
Шкалу крутил. Эффект крутиться на одной половине панели. Не идут ,перезагрузка. Позже логи попробую выложить.

**Comment by dina16121974** [comment]
Не у всех эффектов перезагрузка. Многие в дебаге видно выполняються ,но панель не горит.

**Comment by dina16121974** [comment]
> Не у всех эффектов перезагрузка. Многие в дебаге видно выполняються ,но панель не горит. Чередование мне паяльником надо перетыкивать,хер с ним 2 панели есть ,на одной нормально. Подожду от Вас когда выбор пинов добавите и может чередование цвета.

**Comment by dina16121974** [comment]
> Эффекты которые ,не идут. 1 ,10 ,12 ,15 (половина панели работает) ,20 ,21 ,24 ,25 ,28 ,29 ,33 ,37 ,42 ,42 ,44 ,47 ,49 ,51, 56, 57, 59, 60, 65, 69, 70 (половина панели работает) ,71, 73, 254, 255. И еще чередование цветов ,не то. Надо где то настройку сделать.

**Comment by dina16121974** [comment]
Закрыть можно.

**Comment by vortigont** [comment]
настройка реализована в 04d081a
