### ISSUE TITLE
Тм1637  при подаче питания, должен показывать , текущий ип адрес для подключения или куда подключен.

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#4]

**Comment by vortigont** [comment]
там вроде в конфиге есть параметр `TM_SHOW_BANNER`, должен показывать адрес при старте, проверьте.
Можно в будущем его перенести в настройку в вебморде.

**Comment by dina16121974** [comment]
Да все заработало. Спасибо. Я забыл про эту настройку. Вроде 1637 работает ,теперь корректно.
