### ISSUE TITLE
Сенсорная кнопка TP223 - некорректная работа после перезагрузки

### ISSUE THREAD

**Issue by BashSer** [vortigont/FireLamp_JeeUI#51]
После перезагрузки по питанию кнопка может работать некорректно - некоторые действия могут "забываться".

Помогает зайти в настройки кнопки веб-интерфейса, переключить флажок выкл\вкл и при необходимости проверить действия щелчков. Если что-то не работает, то зайти в это действие и выйти. Например ```OFF: 1 Click - ON`` -> редактировать -> не изменяя параметров просто нажать обновить

>vortigont:
>"Кнопку" я сейчас переписываю целиком, пока не буду смотреть что там.

**Comment by vortigont** [comment]
кнопка переписана целиком
