### ISSUE TITLE
эффект 17, пятнашки - иногда свигается только один ряд

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#6]
Ветка фит 17 эффект ,пятнашки. Перемещение , только в одном ряду ,по одной оси. Должно быть перемещение ,во всех рядах по 2 осям (горизонталь ,вертикаль).

**Comment by vortigont** [comment]
да, бывает так, тоже замечал. Надо посмотреть более внимательно как там перебор сделан.
