### ISSUE TITLE
TM display - при регулировке звука/яркости отображает двоеточие вместо значений

### ISSUE THREAD

**Issue by vortigont** [vortigont/FireLamp_JeeUI#63]

**Comment by dina16121974** [comment]
Вы не так поняли ,отображает все нормально ,только двоеточие добавилось ,его вроде не было. Сейчас вот так Sn:6 или br:6 ,а было вроде Sn 6 или br 6

**Comment by vortigont** [comment]
это не баг, так красивее :)
