### ISSUE TITLE
есп32s3 128х64

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#73]
Вообщем ,тм clk пин 40 ,тм dio пин 41 ,микрофон пин 38. Глядите за точками на дисплее. Начало без микрофона ,потом микрофон вкл. Точки не синхронно мигают. Может сами в исуе добавите ,как вам понятно. Видео у Вас в личке в телеграме.

**Comment by vortigont** [comment]
Fixed
