### ISSUE TITLE
Демо останавливается при включенном флажке "Плавное переключение эффектов"

### ISSUE THREAD

**Issue by dina16121974** [vortigont/FireLamp_JeeUI#89]
Вообщем через 1.5 суток непрерывного теста ,лампа зависла на одном эффекте ,дальше демо не переключает. Откл. чекрыжик ,демо идет дальше ,вкл. чекрыжик висит на одном эффекте. Может нафиг этот чекрыжик? И без него переживем?

**Comment by vortigont** [comment]
вероятно это проблема всё с тойже либой планировщика

**Comment by dina16121974** [comment]
В телеге написал ,как таковой проблемы и как бы нет.

**Comment by dina16121974** [comment]
Если яркость на 4 выставлять ,в принципе плавное переключение можно пока оставить как есть. Посмотрим дальше ,после новых наворотов.

**Comment by vortigont** [comment]
fixed in 8b343542faac7c3577c382faf3cf74f3a4869d96
